### ISSUE TITLE
MiningLocations error

### ISSUE THREAD

**Issue by amgmacht** [trclassic92/tr-mining#6]
[ script:tr-mining] SCRIPT ERROR: @tr-mining/server/main.lua:136: bad argument https://github.com/trclassic92/tr-mining/issues/1 to 'pairs' (table expected, got nil)
[ script:tr-mining] > fn (@tr-mining/server/main.lua:136)

**Comment by trclassic92** [comment]
? Can you give context on when the error is happening

**Comment by amgmacht** [comment]
it happens when you have finished all the points and want to start again from the beginning then this error comes and you can no longer dismantle you have to restart the script once and then it works again

**Comment by trclassic92** [comment]
I know I fixed this issue a while ago are you sure you have updated since then?

**Comment by amgmacht** [comment]
Yes, I saw the issue you had last and exchanged the lines and then the error message was gone, but you still can't start dismantling from the beginning again.

**Comment by trclassic92** [comment]
Can you show a video of this happening because everything is working fine on my side of things.

**Comment by amgmacht** [comment]
[    script:tr-mining] SCRIPT ERROR: @tr-mining/server/main.lua:136: bad argument #1 to 'pairs' (table expected, got nil)
[    script:tr-mining] > fn (@tr-mining/server/main.lua:136)


I have all the points again expired and then came the error in the server console again and others can not collect because I have already mined all the points, video coming soon

**Comment by trclassic92** [comment]
@amgmacht Were you ever able to upload a video?

If you do have a video or a way to somehow so this issue then you are more than welcome to open a ticket on my discord or you can use the open support channels that I have in my discord and just tag me when you do.

https://discord.gg/zRCdhENsHG  <-- That is the invite link to the discord if you aren't already in it..

With that being said I am going to be closing this issue.
